-- ===============================================================================
-- Supabase (Postgres) Schema for irrigation-monitor
-- Generated: 2026-05-19
-- Source: SQLite database (irrigation.db) with 17 tables
--
-- This file creates the complete database schema for the irrigation-monitor
-- project in Supabase (PostgreSQL). It is designed to be pasted directly into
-- the Supabase SQL Editor.
--
-- Key translations from SQLite to Postgres:
-- - INTEGER AUTOINCREMENT → BIGINT GENERATED BY DEFAULT AS IDENTITY
-- - INTEGER (for Unix timestamps) → BIGINT (future-proof for epochs beyond 2038)
-- - REAL → DOUBLE PRECISION
-- - TEXT → TEXT (Postgres TEXT is unbounded like SQLite)
-- - DEFAULT (unixepoch()) → DEFAULT (EXTRACT(EPOCH FROM NOW())::BIGINT)
-- - DATETIME → BIGINT (normalized to Unix epoch for consistency)
--
-- Row Level Security (RLS) is NOT enabled on these tables. This is a single-user
-- system with service-role access. RLS can be added later if multi-user access
-- is needed.
-- ===============================================================================

BEGIN;

-- ============================================================================
-- Core monitoring tables (Phase 0)
-- ============================================================================

-- Zone state transitions (on/off events)
CREATE TABLE zone_state_log (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  timestamp BIGINT DEFAULT (EXTRACT(EPOCH FROM NOW())::BIGINT),
  controller TEXT NOT NULL,
  zone_id TEXT NOT NULL,
  relay_id INTEGER,
  state TEXT,
  run_seconds INTEGER,
  flow_gpm DOUBLE PRECISION
);

COMMENT ON TABLE zone_state_log IS 'Tracks every zone on/off transition from Hydrawise polling';
COMMENT ON COLUMN zone_state_log.timestamp IS 'Unix epoch seconds';

-- Tank level estimates
CREATE TABLE tank_level_log (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  timestamp BIGINT DEFAULT (EXTRACT(EPOCH FROM NOW())::BIGINT),
  level_gallons DOUBLE PRECISION,
  source TEXT DEFAULT 'calculated'
);

COMMENT ON TABLE tank_level_log IS 'Tank level estimates calculated from flow events and ditch fill rate';
COMMENT ON COLUMN tank_level_log.source IS 'calculated | sensor (Phase 7)';

-- Completed watering events
CREATE TABLE watering_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  timestamp BIGINT NOT NULL DEFAULT (EXTRACT(EPOCH FROM NOW())::BIGINT),
  controller TEXT NOT NULL,
  zone_id TEXT NOT NULL,
  relay_id INTEGER,
  duration_seconds INTEGER,
  gallons DOUBLE PRECISION,
  flow_gpm DOUBLE PRECISION,
  source TEXT,
  flow_source TEXT NOT NULL DEFAULT 'calculated',
  flow_quality TEXT NOT NULL DEFAULT 'calculated'
);

COMMENT ON TABLE watering_events IS 'Completed zone runs with gallons calculated from configured GPM × duration';
COMMENT ON COLUMN watering_events.flow_source IS 'Always calculated (real-time flow not available via Hydrawise API)';

-- System warnings and alerts
CREATE TABLE warnings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  timestamp BIGINT DEFAULT (EXTRACT(EPOCH FROM NOW())::BIGINT),
  type TEXT,
  message TEXT,
  zone_id TEXT,
  controller TEXT,
  resolved INTEGER DEFAULT 0
);

COMMENT ON TABLE warnings IS 'Low tank warnings, ditch failure alerts, zone/controller suspensions';

-- ============================================================================
-- ET calculation tables (Phase 1)
-- ============================================================================

-- Daily ET from Open-Meteo
CREATE TABLE et_log (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  date TEXT,
  et_inches DOUBLE PRECISION,
  temp_high_f DOUBLE PRECISION,
  temp_low_f DOUBLE PRECISION,
  humidity_pct DOUBLE PRECISION,
  wind_mph DOUBLE PRECISION,
  solar_rad DOUBLE PRECISION,
  source TEXT,
  created_at BIGINT DEFAULT (EXTRACT(EPOCH FROM NOW())::BIGINT)
);

COMMENT ON TABLE et_log IS 'Daily evapotranspiration from Open-Meteo API via Penman-Monteith calculation';
COMMENT ON COLUMN et_log.date IS 'ISO date string YYYY-MM-DD';

-- ============================================================================
-- Zone coefficient learning tables (Phase 2)
-- ============================================================================

-- Per-zone Kz learning coefficients
CREATE TABLE zone_coefficients (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  zone_id TEXT NOT NULL,
  controller TEXT NOT NULL,
  kz_value DOUBLE PRECISION DEFAULT 1.0,
  last_updated BIGINT,
  observation_count INTEGER DEFAULT 0
);

COMMENT ON TABLE zone_coefficients IS 'Per-zone water need multipliers learned from user feedback';

-- Daily target vs actual analysis
CREATE TABLE zone_daily_analysis (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  date TEXT NOT NULL,
  zone_id TEXT NOT NULL,
  controller TEXT NOT NULL,
  et_inches DOUBLE PRECISION,
  kz_value DOUBLE PRECISION,
  target_gallons DOUBLE PRECISION,
  actual_gallons DOUBLE PRECISION,
  delta_gallons DOUBLE PRECISION,
  delta_pct DOUBLE PRECISION,
  notes TEXT,
  created_at BIGINT DEFAULT (EXTRACT(EPOCH FROM NOW())::BIGINT)
);

COMMENT ON TABLE zone_daily_analysis IS 'Daily report: target vs actual water application per zone';

-- ============================================================================
-- SMS and observation feedback tables (Phase 3 & 5)
-- ============================================================================

-- SMS message log
CREATE TABLE sms_log (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  timestamp BIGINT DEFAULT (EXTRACT(EPOCH FROM NOW())::BIGINT),
  direction TEXT,
  from_number TEXT,
  to_number TEXT,
  body TEXT,
  media_url TEXT,
  parsed_command TEXT,
  zone_id TEXT,
  session_token TEXT
);

COMMENT ON TABLE sms_log IS 'All inbound and outbound SMS messages via Twilio';

-- User feedback observations
CREATE TABLE observations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  timestamp BIGINT DEFAULT (EXTRACT(EPOCH FROM NOW())::BIGINT),
  zone_id TEXT NOT NULL,
  controller TEXT NOT NULL,
  user_name TEXT,
  rating TEXT,
  et_avg_10day DOUBLE PRECISION,
  gallons_per_day_at_time DOUBLE PRECISION,
  kz_before DOUBLE PRECISION,
  kz_after DOUBLE PRECISION,
  follow_up_date TEXT,
  session_token TEXT
);

COMMENT ON TABLE observations IS 'User ratings (GOOD/LOW/HIGH) that drive Kz coefficient adjustments';

-- Scheduled check-in reminders
CREATE TABLE scheduled_reminders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  zone_id TEXT NOT NULL,
  controller TEXT NOT NULL,
  reminder_date TEXT NOT NULL,
  reminder_type TEXT,
  status TEXT DEFAULT 'pending',
  created_at BIGINT DEFAULT (EXTRACT(EPOCH FROM NOW())::BIGINT)
);

COMMENT ON TABLE scheduled_reminders IS 'Monthly MMS check-in schedule per zone';

-- User preferences
CREATE TABLE user_preferences (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_name TEXT NOT NULL,
  phone_number TEXT,
  language TEXT DEFAULT 'en',
  role TEXT DEFAULT 'other',
  created_at BIGINT DEFAULT (EXTRACT(EPOCH FROM NOW())::BIGINT),
  updated_at BIGINT DEFAULT (EXTRACT(EPOCH FROM NOW())::BIGINT)
);

COMMENT ON TABLE user_preferences IS 'Per-user language, phone, role for SMS recipients';

-- ============================================================================
-- Flow calibration table (Phase 4a - repurposed)
-- ============================================================================

-- Tank-drawdown GPM calibration measurements
CREATE TABLE flow_calibration_log (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  timestamp BIGINT NOT NULL,
  controller_id INTEGER NOT NULL,
  zone_relay INTEGER NOT NULL,
  duration_sec INTEGER NOT NULL,
  tank_gpm DOUBLE PRECISION,
  tank_drawdown_gal DOUBLE PRECISION,
  ditch_fill_gal DOUBLE PRECISION,
  notes TEXT
);

COMMENT ON TABLE flow_calibration_log IS 'Tank-drawdown calibration measurements for per-zone GPM updates';
COMMENT ON COLUMN flow_calibration_log.timestamp IS 'Unix epoch seconds (normalized from DATETIME)';

CREATE INDEX idx_flow_cal_zone ON flow_calibration_log (controller_id, zone_relay, timestamp DESC);

-- ============================================================================
-- Ditch health table (Phase 6)
-- ============================================================================

-- Ditch water health check results
CREATE TABLE ditch_health_log (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  timestamp BIGINT DEFAULT (EXTRACT(EPOCH FROM NOW())::BIGINT),
  zone_id TEXT,
  controller TEXT,
  flow_detected INTEGER,
  flow_gpm DOUBLE PRECISION,
  result TEXT,
  notes TEXT
);

COMMENT ON TABLE ditch_health_log IS 'Daily ditch water flow verification results';

-- ============================================================================
-- ESP32 sensor table (Phase 7)
-- ============================================================================

-- ESP32 ultrasonic sensor readings
CREATE TABLE tank_sensor_log (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  timestamp BIGINT DEFAULT (EXTRACT(EPOCH FROM NOW())::BIGINT),
  depth_inches DOUBLE PRECISION,
  level_gallons DOUBLE PRECISION,
  source TEXT DEFAULT 'calculated'
);

COMMENT ON TABLE tank_sensor_log IS 'ESP32 ultrasonic sensor readings (~$20 hardware, Phase 7)';

-- ============================================================================
-- Zone GPM override tables (2026-05-19 feature)
-- ============================================================================

-- Runtime GPM overrides (operator edits)
CREATE TABLE zone_gpm_overrides (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  controller TEXT NOT NULL,
  zone_id TEXT NOT NULL,
  gpm DOUBLE PRECISION NOT NULL CHECK (gpm >= 0),
  reason TEXT,
  updated_at BIGINT NOT NULL DEFAULT (EXTRACT(EPOCH FROM NOW())::BIGINT),
  UNIQUE(controller, zone_id)
);

COMMENT ON TABLE zone_gpm_overrides IS 'Operator-set GPM overrides; zones.config.js holds defaults, this holds runtime edits';
COMMENT ON COLUMN zone_gpm_overrides.gpm IS 'Must be non-negative; capped at 100 by application logic';

-- GPM change audit log
CREATE TABLE zone_gpm_change_log (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  controller TEXT NOT NULL,
  zone_id TEXT NOT NULL,
  old_gpm DOUBLE PRECISION,
  new_gpm DOUBLE PRECISION,
  reason TEXT,
  changed_at BIGINT NOT NULL DEFAULT (EXTRACT(EPOCH FROM NOW())::BIGINT)
);

COMMENT ON TABLE zone_gpm_change_log IS 'Audit trail for all GPM changes (sets and resets)';
COMMENT ON COLUMN zone_gpm_change_log.old_gpm IS 'NULL = was using config default';
COMMENT ON COLUMN zone_gpm_change_log.new_gpm IS 'NULL = reset to config default';

CREATE INDEX idx_gpm_change_log_zone ON zone_gpm_change_log (controller, zone_id, changed_at DESC);

COMMIT;

-- ===============================================================================
-- Schema creation complete
-- ===============================================================================
--
-- Next steps:
-- 1. Verify all 16 tables created (17 in SQLite minus sqlite_sequence internal table)
-- 2. Import CSV data via Supabase Studio Table Editor
-- 3. Verify row counts match migrations/data_export/MANIFEST.txt
--
-- Note: sqlite_sequence is an SQLite internal table and is not migrated.
-- ===============================================================================
